// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj94z9EdXWln4PFYANimY_cwnyQwp6LQ8',
    appId: '1:1048698255969:web:ac3c946358b9a5bb148820',
    messagingSenderId: '1048698255969',
    projectId: 'insuraease-4bf92',
    authDomain: 'insuraease-4bf92.firebaseapp.com',
    storageBucket: 'insuraease-4bf92.firebasestorage.app',
    measurementId: 'G-VEGBPXNBPT',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj94z9EdXWln4PFYANimY_cwnyQwp6LQ8',
    appId: '1:1048698255969:web:52c687cce046822b148820',
    messagingSenderId: '1048698255969',
    projectId: 'insuraease-4bf92',
    authDomain: 'insuraease-4bf92.firebaseapp.com',
    storageBucket: 'insuraease-4bf92.firebasestorage.app',
    measurementId: 'G-HS00X74BKF',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT2KqRz2_zQ6Vf6T8Jr25AABvyGVB7e_I',
    appId: '1:1048698255969:ios:f8c8bda1b1641580148820',
    messagingSenderId: '1048698255969',
    projectId: 'insuraease-4bf92',
    storageBucket: 'insuraease-4bf92.firebasestorage.app',
    iosBundleId: 'com.example.insuraEase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT2KqRz2_zQ6Vf6T8Jr25AABvyGVB7e_I',
    appId: '1:1048698255969:ios:f8c8bda1b1641580148820',
    messagingSenderId: '1048698255969',
    projectId: 'insuraease-4bf92',
    storageBucket: 'insuraease-4bf92.firebasestorage.app',
    iosBundleId: 'com.example.insuraEase',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT_yB-LrGz4h6xk5TQzshvN-8zqzke_eU',
    appId: '1:1048698255969:android:790706aaa33e764f148820',
    messagingSenderId: '1048698255969',
    projectId: 'insuraease-4bf92',
    storageBucket: 'insuraease-4bf92.firebasestorage.app',
  );

}